version: '3.8'
services: #все контейнеры писать внутри
    web-myblogkristin:
        build:
            context: . # загрузка DockerFile
        container_name: web-myblogkristin #название контейнера
        volumes: # мантирование каталогов
            - ./:/var/www/html/
        restart: always # всегда перезагружать если остановился
        depends_on: # запускать этот контейнер после того как запуститься db
            - db-myblogkristin
        extra_hosts:
            - "myblogkristin.test:127.0.0.1"
        ports:
            - "82:80"

    db-myblogkristin:
        image: mysql
        container_name: db-myblogkristin
        tty: true
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: myblogkristin
            MYSQL_USER: myblogkristin
            MYSQL_PASSWORD: root
        restart: always
        ports:
            - "3382:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - db-myblogkristin
        environment:
            PMA_HOST: db-myblogkristin
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - '89:80'
        restart: always
