version: '3.8'
services: #все контейнеры писать внутри
    web-spa:
        build:
            context: . # загрузка DockerFile
        container_name: web-spa #название контейнера
        volumes: # монтирование каталогов
            - ./:/var/www/html/
        restart: always # всегда перезагружать если остановился
        depends_on: # запускать этот контейнер после того как запуститься db
            - db-spa
        extra_hosts:
            - "spa.test:127.0.0.1"
        ports:
            - "83:80"

    db-spa:
        image: mysql
        container_name: db-spa
        tty: true
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: spa
            MYSQL_USER: spa
            MYSQL_PASSWORD: root
        restart: always
        ports:
            - "3383:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-spa
        links:
            - db-spa
        environment:
            PMA_HOST: db-spa
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        ports:
            - '89:80'
        restart: always
